name: Test and Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout novamente para garantir que o código esteja sincronizado

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.TEAM_ID }}  # Certifique-se de usar 'vercel-org-id' em vez de 'vercel-team-id'
  deploys3:
      runs-on: ubuntu-latest

      steps:
      # 1. Checkout o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3
  
      # 2. Configuração do Node.js para build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
  
      # 3. Instalar dependências do projeto
      - name: Install dependencies
        run: npm install
  
      # 4. Build do projeto ReactJS
      - name: Build ReactJS project
        run: npm run build
  
      # 5. Deploy para o S3
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: "zlo-shop"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "build" # Diretório gerado pelo build do React
