name: Test and Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Force Git clone
        run: |
          git init
          git remote add origin https://github.com/WesleySardi/projeto-conclusao-curso-frontend.git
          git fetch
          git reset --hard origin/master  # Ou 'master', dependendo da sua branch principal

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.TEAM_ID }}  # Certifique-se de usar 'vercel-org-id' em vez de 'vercel-team-id'
